from .s01_title import TitleScene
from .s02_continuity import ContinuityScene
from .s03_navier_stokes import NavierStokesScene
from .s04_airfoil_intro import AirfoilIntroScene
from .s05_potential_flow import PotentialFlowScene
from .s06_boundary_layer import BoundaryLayerScene
from .s07_bernoulli_lift import BernoulliLiftScene
from .s08_reynolds import ReynoldsScene
from .s09_summary import SummaryScene
